package student.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import student.dao.AdminDao;
import student.dto.Admin;
@WebServlet("/signUp")
public class AdminSignup extends HttpServlet

{
@Override
protected void doPost(HttpServletRequest req,HttpServletResponse res) throws ServletException, IOException
{
	
	String name =req.getParameter("AdminName");// passing key from adminsignup jsp
	String email =req.getParameter("AdminEmail");
	String password =req.getParameter("AdminPassword");
	
	Admin admin=new Admin();// dont want to set id because it is autogenerated
	admin.setAdminName(name);
	admin.setAdminEmail(email);// email should be unique because it is diff for diff students
	// therfore in admin class using @column unique
	admin.setAdminPassword(password);
	
	// to save to database
	new AdminDao().AdminSignUp(admin);// passing admin obj to adminsignup method
	
	// after signup redirect to login page
	
	req.getRequestDispatcher("AdminLogin.jsp").forward(req, res);
}
}